### PR TITLE
Blue links

### PR DESCRIPTION
**Pull request by jgthms**
This is a **new feature | improvement | bugfix | documentation fix**.

### CODE REVIEW

**Comment by skbolton** [comment]
I tried updating to a new version of bulma and all the links and accent colors turned blue. Is there a variable or configuration that I can do to change the colors back to the primary color? I'd love to use some of the new classes and things but the color change breaks the aesthetic of my app somewhat

**Comment by ctolkien** [comment]
@skbolton 

`$link: $primary;`

**Comment by skbolton** [comment]
haha beautiful I guess I should have just gone with the hopeful obvious route! This framework only gets better thanks @jgthms

**Comment by jgthms** [comment]
@skbolton There was a blog post in which I explained how to maintain the old styles: https://bulma.io/2017/10/09/roses-are-red-links-are-blue/

Sorry that it wasn't clear!

**Comment by skbolton** [comment]
Awesome that also answers my question on why now my link buttons are the primary color! Is-text it is

**Pull request merged**
