### PR TITLE
Add feature: is-expanded to navbar-item #1255

### PR DESCRIPTION
**Pull request by doatech**
This is an **improvement**.

Added `.is-expanded` modifier for `navbar-item` suggested in [#1255](https://github.com/jgthms/bulma/issues/1255)

### Proposed solution

This is a PR for issue [#1255](https://github.com/jgthms/bulma/issues/1255) using basic solution suggested by [jgthms](https://github.com/jgthms).

### Testing Done

Done locally using [Laravel 5.5](https://laravel.com/docs/5.5/mix)'s default mix `npm run dev` & `npm run prod`

### CODE REVIEW

**Comment by jgthms** [comment]
Just need to fix the changelog conflict.

**Comment by doatech** [comment]
@jgthms fixed!

**Comment by amir20** [comment]
@jgthms I came to this issue and tried using `.is-expanded` on `.navbar-item`. However, it wasn't working. After some debugging, I realized `.navbar-start` doesn't have a size so the flex box was never growing. Do you know what needs to happen to `.navbar-start` for this to work?

**Comment by doatech** [comment]
@amir20 is suggest adding `flex-grow: 1; flex-shrink: 1;` to your `.navbar-start`, but that will make the `.navbar-start` expanded too. Or maybe use just `.navbar-item`-s without `.navbar-start`.

**Pull request merged**
