### PR TITLE
Fixes #107: Inline-flex properly calculates its content size

### LINKED ISSUE #107: Tabs component alignment and small screens
Center aligned tabs can end up with their leftmost item cut off. Right aligned tabs get no scrollbar.

### PR DESCRIPTION
**Pull request by lostm1nd**
Block element does not overflow the tab container.

### CODE REVIEW

**Comment by jgthms** [comment]
What is the purpose behind this one? It prevents the tab border to go across the whole width.

**Comment by lostm1nd** [comment]
Could you share a screenshot of this because I do see the border across all the tabs.
tabs-border

**Comment by jgthms** [comment]
Should be like this:

screen shot 2016-03-27 at 11 27 01 am

**Comment by lostm1nd** [comment]
Totally overlooked this. Another way to stretch the .tabs ul is to use some of the proposed width properties (min-content does the job) but they are not that well supported.

**Comment by jgthms** [comment]
The tab structure has changed.

**Pull request closed without merging**
