### PR TITLE
[Closes #1325] Documentation Search

### LINKED ISSUE #1325: Search for Bulma docs
Please add a search functionality for Bulma docs.

### PR DESCRIPTION
**Pull request by patrickdaze**
This is a **documentation fix**.

### Proposed solution
Using Algolia's [DocSearch](https://community.algolia.com/docsearch/) for scraping, indexing, understanding the documentation’s hierarchy, and displaying search results. It would close #1325.

The scraper indexes the latest/current documentation hosted on https://bulma.io/. It also indexes previous versions of the documentation hosted on https://versions.bulma.io/ starting at version 0.6.2 (since there was no search before this version).

### Tradeoffs
The solution relies on a third-party (Algolia) to scrape and index new content. DocSearch is however used by many reputable projects such as [Bootstrap](https://getbootstrap.com/docs/4.0/getting-started/introduction/), [Vue.js](https://vuejs.org/v2/guide/), [React](https://reactjs.org/), and [many others](https://github.com/algolia/docsearch-configs/tree/master/configs).

The alternative is to use something like [jekyll-algolia](https://community.algolia.com/jekyll-algolia/) which would rebuild a new index before deploying a new documentation version. It however requires more development, and configuration. Mainly it would require custom hooks written in Ruby to reorganize the content before sending it to Algolia.

### Testing Done
Most of the solution relies on the DocSearch JavaScript and styles. Not much custom code was written. Initial testing is done using the [docsearch-scraper](https://github.com/algolia/docsearch-scraper).

For testing locally, [append the Algolia testing app to your Jekyll configuration](https://github.com/patrickdaze/bulma/commit/b5363482ef7b71018bde2b0684a10cb3cf229afb#comments).

### Launch Requirements
- [x] Create initial DocSearch frontend implementation
- [x] Create the [DocSearch configuration](https://github.com/patrickdaze/docsearch-configs/tree/bulma-configuration)
- [ ] Collaborate with Algolia to implement the DocSearch configuration ([comment about this below](https://github.com/jgthms/bulma/pull/1622#issuecomment-360015138))
- [ ] Finalize frontend design (this PR / discussion at #1325)
- [ ] Update `_config.yml` with key and index provided by Algolia
- [ ] Update repo's documentation (if required)

### CODE REVIEW

**Comment by patrickdaze** [comment]
If Bulma's team (@jgthms?) agrees to use DocSearch, I suggest that the next step would me for me to open a PR with [the DocSearch configuration](https://github.com/patrickdaze/docsearch-configs/commits/bulma-configuration). This would initiate the conversation with Algolia.

Alternatively the Bulma team can start a conversation by filling-in [the form on the DocSearch website](https://community.algolia.com/docsearch/). Once Algolia replies, Bulma's team can mention [the configuration branch](https://github.com/patrickdaze/docsearch-configs/commits/bulma-configuration).

**Comment by patrickdaze** [comment]
@jgthms is this PR heading in the right direction?

There's just two main things left: [agree/disagree with design](https://github.com/jgthms/bulma/issues/1325#issuecomment-360014964), and [initialize conversation with Algolia](https://github.com/jgthms/bulma/pull/1622#issuecomment-360015138).

**Comment by patrickdaze** [comment]
I noticed the website layout has change since I created this PR. If still interested, let me know and I can update this PR to match it.

cc @jgthms

**Comment by san-kumar** [comment]
This was a really good thing. Right now it takes forever to search something as is-grouped, is-gapless, etc. Any updates on this?

**Comment by wtfluckey** [comment]
🙏 Please, please, please!

**Comment by Maxhodges** [comment]
wow what a turd for not even replying to your PR. I've lost all respect for this guy.

**Comment by ahstro** [comment]
How has this not been merged yet?

**Comment by Shipow** [comment]
Hello Bulma team, I'm working for Algolia and I'm super excited to see DocSearch on this docs!
Do you need any help to get this PR merged? Is there any issue I could help to solve with the index?
Let me know ^^

**Comment by Maxhodges** [comment]
please note

https://github.com/jgthms/bulma/issues/2374

**Comment by Shipow** [comment]
Oh, wow, sensing a bit of frustration there :)
I've been familiar with that feeling in the past but it's easy to get lost in issues, PR, priorities, life and stuff.
Of course I'd recommend the [great talk of Fat about maintaining a successful open source project](https://www.youtube.com/watch?v=UIDb6VBO9os) to get a better idea on how hard it can be. Open source is full of compromises and challenges. I believe Bulma is an awesome project that will continue to grow at it's own pace! Respect for everything already achieved.

**Comment by patrickdaze** [comment]
As this thread has proven, the lack of search for the open source Bulma project is frustrating for the community. This is why @thomasedwards and myself (@patrickdaze) have been working on two projects.

The first is [Bulma Search](https://github.com/thomasedwards/bulmasearch). It provides indexing and and search through Algolia.

The second is [Search for Bulma : Chrome Extension](https://github.com/patrickdaze/bulma-search-chrome), a chrome extension that uses Bulma Search.

Both projects are not affiliated with nor developed by the core Bulma team. Feel free to send us PRs.

**Comment by GMaiolo** [comment]
Why hasn't anything related to docs search been implemented in more than 2 years?

It's a **major** issue as far as I see, because it doesn't allow people to learn the framework in a comfortable way. I find myself google-guessing terms to get to the right place and it's extremely frustrating.

**Comment by a-kriya** [comment]
@patrickdaze Can probably be closed now : ]

**Comment by patrickdaze** [comment]
✌️

**Pull request closed without merging**
