### PR TITLE
Add text color classes

### PR DESCRIPTION
**Pull request by guillaumemorin**

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Ping @jgthms — I was after this earlier :)

**Comment by jgthms** [comment]
Hi @guillaumemorin 

You need to rebuild the CSS files.

**Comment by guillaumemorin** [comment]
Hi @jgthms,
'npm run build' give me a segmentation fault error, like here https://github.com/jgthms/bulma/issues/188
Do i miss something?

**Comment by jeppech** [comment]
@guillaumemorin As mentioned in #188, try downgrading to/adding node-sass@3.4.2 in you're packages.json, this should make it compile again.

**Comment by guillaumemorin** [comment]
@jeppech works well indeed, thx a lot !

**Comment by alexjab** [comment]
Hi,

any update on this PR ? That would definitely be something nice to have.

**Comment by gbourgneuf** [comment]
It would be nice to have it.
But I noticed a little issue with the colors names: white and black are transformed to #FFF and #000 when compiling.
To rectify this you should also change the $colors variables declaration into the file /utilities/variables.sass to (notice the quotes for white and black declarations):

`$colors: ('white': ($white, $black), 'black': ($black, $white), light: ($light, $light-invert), dark: ($dark, $dark-invert), primary: ($primary, $primary-invert), info: ($info, $info-invert), success: ($success, $success-invert), warning: ($warning, $warning-invert), danger: ($danger, $danger-invert)) !default`

**Comment by jgillich** [comment]
+1, can we get this merged?

**Comment by jgthms** [comment]
Sorry the guidelines have changed. Can you only include your `sass/base/helpers.sass` changes and I'll merge this PR.

**Comment by guillaumemorin** [comment]
@jgthms Done ! Is everything ok ?

**Comment by jgthms** [comment]
Cheers!

**Pull request merged**
