### PR TITLE
bulma-tagsfield - multi-line tags input control (extension)

### PR DESCRIPTION
**Pull request by vyachkonovalov**
This is a **new documentation fix**.

### Proposed solution

I'd like to add my extension to the extensions list. But I don't know values for `width` and `height`, and how to add link to the image (extension screenshot).

### Tradeoffs

Tagsfield is a lighter version for [tags-input](https://github.com/CreativeBulma/bulma-tagsinput). And it uses `span[contenteditable]` instead of `input`.

### Testing Done

None.

### Changelog updated?

No.

### CODE REVIEW

**Comment by vyachkonovalov** [comment]
bulma-tagsfield_screenshot

**Comment by jgthms** [comment]
I meant in the PR.

**Comment by vyachkonovalov** [comment]
😅 oh, now I see, images are at docs/images

**Comment by jgthms** [comment]
Make sure the width and height match what you’ve written in the Yaml configuration.

**Pull request merged**
