### PR TITLE
Add Bulma Templates to readme

### PR DESCRIPTION
**Pull request by dansup**
This is a **new feature | improvement | bugfix | documentation fix**.

### CODE REVIEW

**Comment by jgthms** [comment]
Thanks but can you put it at the bottom of the list?

**Comment by dansup** [comment]
@jgthms Sure thing.

**Comment by jgthms** [comment]
There’s merge conflicts apparently.

**Comment by dansup** [comment]
@jgthms Had issues with Github desktop, recreated in #1379

**Pull request closed without merging**
