### PR TITLE
WIP: Add footer buttons to .card

### PR DESCRIPTION
**Pull request by timacdonald**
This is a **new feature**. Here's what we are doing:

screen shot 2018-01-30 at 7 21 01 pm

Currently the `.card` footer only allows `.card-footer-item`. I always want to be able to use `.button` elements in the footer instead of just plain links. This PR is a **WIP** and is more of just a suggestions of a possibility. I'm not a CSS ninja - so there could be things wrong here.

Suggestions and feedback welcomed.

### Proposed solution

Here is what I've done to achieve the current SASS...

Duplicated `.button` and then...

- Removed `+control`.
- Removed `+unselectable` (although perhaps this should be retained).
- Removed `border:` stuff.
- Removed `box-shadow:` stuff.
- Removed `.is-outlined` stuff.
- Removed **sizes**.
- Removed `.is-fullwidth`.
- Removed `.is-rounded`.
- Adjusted to match `.card-footer-item`.

### Tradeoffs

This would create a kind of `.card-footer-*` pattern which is perhaps not the best solution. Perhaps a more element agnostic solution would be better for the `.card-footer`. Going forward with this pattern would mean a (possibly substantial) increase in CSS with each new element that is added to the pattern.

@nedjo suggested this here: https://github.com/jgthms/bulma/issues/1376

### Testing Done

I've created [this codepen](https://codepen.io/timacdonald/pen/bLGXxd) with the current built css with a few examples to look at.

## Need input from Jeremy

- [ ] Can we use the button variables so we don't double up on existing rules?
- [ ] The `.card-footer-item` right border when mixing. Check out the blue, white, yellow example. I feel the white buttons right border looks weird?
- [ ] Codepen created with all possible variations to check for possible issues.
- [ ] Individual `card-footer-*` items or a more element agnostic approach.
- [ ] Ensure all existing button variations work, such as loading icon, disabled etc.

### Related

https://github.com/jgthms/bulma/issues/948
https://github.com/jgthms/bulma/issues/673

### CODE REVIEW

**Comment by HDVinnie** [comment]
Any update? Will this be merged?

**Comment by timacdonald** [comment]
Nothing from yet - but I think he has been super busy with his new book and the website overhaul. Fingers crossed he might get some spare time soon to have a look at this and let us know his thoughts on this idea.

This will still need a bit of love once he checks it out - so if you wanted to implement it sooner you could checkout [the codepen](https://codepen.io/timacdonald/pen/bLGXxd) example I did up and use the CSS in there. Everything you need is in there to make this work in a current project as it is in this PR.

Or if you are already using a build pipeline for you CSS you could probably just add [the changes](https://github.com/jgthms/bulma/pull/1637/files) to a LESS file.

**Comment by BenBao93** [comment]
This is a very good feature. Found this while trying to search for a solution to do exactly this. Hopefully we can get it merged soon!

**Comment by jthorpe-marco** [comment]
I found one issue when using this fix, but I'm not sure if it's specific to my project.
I had to remove the left and top portions to get my loading icon to be within the button:
```
.card-footer-button.is-loading:after {
    position: absolute;
    /* left: calc(50% - (1em / 2)); */
    /* top: calc(50% - (1em / 2)); */
    position: absolute !important;
}
```

**Comment by timacdonald** [comment]
Thanks for posting @jthorpe-marco This is not a fully complete version, posted here to get a discussion around the idea going. Will definitely need a bit of work and one of the todo items is to create a version of all the button variations already possible, which will include the loading icons. But I didn't wanna put in all that work if it isn't wanted in framework.

If there are any other issues please do post them as it will make it easier to ensure we cover all the bases if it does get merged.

If this idea is wanted I'll happily do more with it. Wait and see I guess :)

**Comment by moonshine31** [comment]
> If this idea is wanted I'll happily do more with it.

I think it's a great idea! But it's been now almost one year since you introduced it.
Regarding if it should be in the framework or not: IMO, definitely - why should a card only have links in its footer. 

Is there a way to push that feature?

**Comment by maximebloch** [comment]
This also applies when you want to disable the footer item. The disabled property is only available for the <button> element, but I want the proper styling of the <a> element in the card-footer-item. 
Where does this issue stand?

**Comment by timacdonald** [comment]
Hey @maximebloch yea that is another thing to add for sure. I'd be happy to add that functionality to this PR. The PR is just waiting for review - I'm happy to push it forward once it has been reviewed.

I've added the disabled state to the original comment todo list.

**Comment by LastxTemplar** [comment]
is this going to be pulled anytime soon?

**Comment by jgthms** [comment]
Hey, thanks for creating this PR. It seems this feature has quite a bit of demand.

The only problem I see is how it's coded. Since you've copied `.button`, there's a _lot_ of duplication. Since these card buttons look and act like regular buttons, but with only a few minor differences, why not use `.button` directly?

Instead of copying the whole thing, just create a new container for these buttons, and apply the differences you want to see.

```html
<div class="card-buttons">
  <button class="button is-info">Cloud</button>
  <button class="button is-static">Or</button>
  <button class="button is-warning">Sun</button>
</div>
```

And then just apply custom styles in this **context**:

```sass
.card-buttons
  .button
    // Custom styles
```

There would be a dependency with `button.sass` but that's fine.

**Comment by AhmedMKamal** [comment]
Just ended up here after some googling, so, if anyone else still struggling with this, here's how I use buttons in card footer.

```html
<footer className="card-footer">
  <p className="card-footer-item is-paddingless">
    <button className="button is-fullwidth">Save</button>
  </p>
  <p className="card-footer-item is-paddingless">
    <button className="button is-fullwidth">Reset</button>
  </p>
</footer>
```

it looks like this

Untitled

**Comment by timacdonald** [comment]
Hey, I don't think I'll be able to get this one off the ground and running. If someone else wants to fork my branch, make the changes suggested by @jgthms  and resubmit it as a PR to benefit Bulma, I'm sure it would be appreciated.

**Pull request closed without merging**
