### PR TITLE
Add menu inverted styles

### PR DESCRIPTION
**Pull request by gfpacheco**
Changes proposed:

Add menu inverted style (`menu is-inverted`).
- [x] Add
- [ ] Fix
- [ ] Remove
- [ ] Update

screen shot 2016-06-17 at 16 03 38

### CODE REVIEW

**Comment by jens1o** [comment]
ping @jgthms

**Comment by jgthms** [comment]
> jens1o commented 22 hours ago
> ping @jgthms

Please don't ping me. I already see all the issues and pull requests. This behaviour will not prioritize this pr over other ones. It might have the invert effect actually.

**Comment by jens1o** [comment]
> jgthms commented 35 minutes ago
> Please don't ping me. I already see all the issues and pull requests. This behaviour will not prioritize this pr over other ones. It might have the invert effect actually.

I am sorry, I did not want to annoy you, but it has so looked for me that you have this repo no longer active, because you have less (public) activity on this repo. I just want to hear your side. It could be possible, that you do not want this repo longer active.

(I am sorry for my bad english anyway)

**Comment by jgthms** [comment]
I'm not sure if this shouldn't be in a larger solution to have a "dark mode" instead across all components.

**Pull request closed without merging**
