### PR TITLE
Fix Webpack build by importing variables in mixins file

### PR DESCRIPTION
**Pull request by dhargitai**
Fixes: jgthms#708
Original commit: kiwicopple/bulma@11a993e
(I couldn't find kiwicopple's repo in the select field when creating pull request so I created a fork myself)

### CODE REVIEW

**Comment by jgthms** [comment]
That file is deprecated. It should be either the initial or derived one.

**Comment by dhargitai** [comment]
My branch was derived from your master branch today.

**Comment by FyiurAmron** [comment]
confirmed. adding that @import satisfies webpack and everything works well again.

**Comment by jgthms** [comment]
It should import `initial-variables`.

**Pull request merged**
