### PR TITLE
Added `!default` to variables

### PR DESCRIPTION
**Pull request by thegitfather**
Hi there! Just a small addition that I think is only useful.

Great work so far!
cu

### CODE REVIEW

**Comment by jgthms** [comment]
What's the purpose exactly?

**Comment by thegitfather** [comment]
This way I can keep your files in my bower_components folder untouched and still overwrite the vars within my style project folder. If I don't set a var of yours then your value will be the default. So no harm, only useful

**Comment by jgthms** [comment]
What about the generated variables? Are they still correctly set, even if you set _your_ custom variables _after_?

https://github.com/jgthms/bulma/pull/42 had the same idea but it didn't work.

**Comment by thegitfather** [comment]
To test this I swapped `$yellow` with `$red` in my `_vars.scss`:
```scss
$temp: $yellow;
$yellow: $red;
$red: $temp;
```
and expected two buttons (`button.button.is-warning` and `button.button.is-danger`) to switch the resulting style. And it worked..

So only important thing is to import the project vars before bulma, e.g.:
```scss
@import 'global-scss/vars';
@import 'global-scss/mixins';
@import 'global-scss/extends';
@import 'global-scss/fonts';
@import 'global-scss/layout';

@import '../bower_components/bulma/bulma';
...
```

**Comment by jgthms** [comment]
You need to add `!default` to `generated-variables.sass` as well.

**Comment by thegitfather** [comment]
Hmm not sure what setup you've tested.. As I see it, the generated variables get assigned with values from the variables file only. So it should be ok to add the `!default` statement only to the variables.sass.. At least it works just fine for my project (`"gulp-sass": "^2.0.1"`)

**Comment by jgthms** [comment]
What about if someone updates the `$primary` color? Or the `$text` one, **before** including bulma?

**Comment by jbrooksuk** [comment]
It wouldn't work, because Bulma would override it anyway?

**Comment by thegitfather** [comment]
It works. E.g. if i add the line `$primary: red;` to my project `_vars.scss` then all links will be red. And as i stated before you always have to set your project vars *before* including bulma.

> `!default` will assign a value only if the variable doesn't already have one. In other words, it prevents a variable from being reassigned.

**Comment by thegitfather** [comment]
has been merged

**Comment by jgthms** [comment]
Hey @thegitfather thanks for your help btw. I restructured all the variables so I took the opportunity to add the `!default` as well.

**Pull request closed without merging**
