### PR TITLE
fieldset disabled styles

### PR DESCRIPTION
**Pull request by samburgers**
Adds disabled styles for `<fieldset disabled>`

### CODE REVIEW

**Comment by stern-shawn** [comment]
👍 
Would love to have this added. As it is now with Bulma, I'm having to manually assign the `disabled` attribute to all elements in a fieldset to ensure expected styling.

**Comment by samburgers** [comment]
Some further explanation to the pull request in hope to get it merged.

### Example markup:
```
<fieldset disabled>
    <div class="field">
        <label class="label">
            Email
        </label>
        <p class="control has-icons-left">
            <input class="input" type="text" placeholder="Email">
            <span class="icon is-small is-left">
                <i class="fa fa-envelope-o"></i>
            </span>
        </p>
    </div>
    <div class="field">
        <label class="label">
            Password
        </label>
        <p class="control has-icons-left">
            <input class="input" type="password" placeholder="Password">
            <span class="icon is-small is-left">
                <i class="fa fa-lock"></i>
            </span>
        </p>
    </div>
    <div class="field is-grouped">
        <p class="control">
            <button class="button is-success">
                Sign In
            </button>
        </p>
        <p class="control">
            <button class="button">
                Login
            </button>
        </p>
    </div>
</fieldset>
```

### Current behaviour:
`<fieldset disabled>` naturally disables form/button elements in all browsers, but they visually appear still active in Bulma:

screen shot 2018-03-31 at 6 07 18 pm

### Proposed change:
This pull request scaffolds the Bulma pre-existing disabled styles for inputs and buttons for when a surrounding `<fieldset>` element is set to disabled.

screen shot 2018-03-31 at 6 07 47 pm

Tested with modifiers such as `is-loading` class:

screen shot 2018-03-31 at 10 26 01 pm

### Reasoning:

Disabling inputs on a fieldset level is handy for multi-step forms, and reactive view frameworks.

### Caveats:

The `<fieldset>` element could also do with a border reset, which I have also submitted a pull request here:
https://github.com/jgthms/minireset.css/pull/12

### Alternatives:

All of this could be alternatively be managed with a `.fieldset` class to perhaps align a bit closer to Bulma conventions, however this could lead to confusion or misalignment with browser behaviour.

**Comment by urin** [comment]
Also it may be better to modify disabled style of [pagination.sass](https://github.com/jgthms/bulma/blob/e04455cfb482f77647eb0c6790f1aa525a3c2f69/sass/components/pagination.sass#L78) also.

**Comment by samburgers** [comment]
Thanks, I just caught that too... pushing down a fix and also resetting the fieldset element. As for adding to the documentation, would you prefer a snippet example in the /forms/general page? Or a small snippet under each "Disabled" section on each form element page?

**Comment by jgthms** [comment]
Both! Since users might be reading one page or the other, but not both.

On the general page you can add a section called “Disabled forms” where you put a whole form. 

On the other pages, just put a link to this new section (with an anchor) with the phrase “You can also disable an input/button/select… by placing it within a disabled form”.

Something like that. Also try to put it behind a flag (search for “vernum” in the docs).

If that’s too much, just put something here, I’ll take care of the rest.

Oh and update the change log please. Thanks! 👍

**Comment by diomed** [comment]
@samburgers do you plan to revisit and update this?

**Comment by samburgers** [comment]
Thanks for the bump, will revis this weekend!

**Comment by diomed** [comment]
@samburgers any news about this?

**Pull request merged**
