### PR TITLE
Bulma Mega Menu Extension

### PR DESCRIPTION
**Pull request by hunzaboy**
Added the bulma-megamenu extension to extension page and uploaded the image in docs/images.

### CODE REVIEW

**Comment by hunzaboy** [comment]
@jgthms, I am planning to write some more extensions. Let me know if you have some in mind.  Thanks

**Comment by jgthms** [comment]
Dimensions should be half of the image, which is 1336x364.

**Comment by hunzaboy** [comment]
@jgthms , Sorry i didn't got you. Are you referring to the slug image? I checked other images but they were  bigger the what i added.

**Comment by jgthms** [comment]
Sorry, can you fix the merge conflicts?

**Comment by hunzaboy** [comment]
Resolved.

**Pull request merged**
