### PR TITLE
build(css): build minified bundle

### LINKED ISSUE #642: Ship Minified to Packagers
Please ship `bulma.min.css` to NPM and Bower in addition to CDN.

### PR DESCRIPTION
**Pull request by jhabdas**
adds a minfied css bundle and uses it

closes #642

### CODE REVIEW

**Comment by jhabdas** [comment]
@jgthms here's why you should do this:

- prevents duplicative work after download, helping ensure bulma always looks like the docs site
- increases page speed of the docs site

**Comment by jgthms** [comment]
Nice work! 👍 

I reckon it would be useful to keep both `bulma.css` and `bulma.min.css`. Some people might want the non-minified version as it's easier to read, if they want to copy some code, or get inspiration, which is easier than navigating through the `.sass` files.

**Comment by jhabdas** [comment]
@jgthms I'll do another sweep at this now that I've got an approval signal. Will ensure everyone gets what they want, and will look to add source maps if it makes sense (otherwise open another issue if needed).

**Comment by jhabdas** [comment]
Still planning to get around to this. Sometime before Brian finishes that novel he's been working on. 😆

**Comment by jhabdas** [comment]
@jgthms Took another pass. Don't see any more work to do. Please let me know if you need anything else to make this merge-friendly. Thanks!

**Comment by mavarazy** [comment]
+1

**Comment by jhabdas** [comment]
@jgthms some individuals would like this merged. care to do us the honors if you're comfortable with the changes?

**Comment by 1zaak** [comment]
Is this gonna be merged or not? My Bulma production build is huge right now and I think this is perfect for my use case @jgthms

**Comment by jhabdas** [comment]
@1zaak I'll leave it to the maintainers to answer that. There's a conflict caused by an addition of css asset fingerprinting which, when I see, is usually a sign of overengineering in the Web tier.

**Comment by 1zaak** [comment]
Sorry I should correct this, it was my own mistake of importing a huge font sass file. Not the maintainers fault @jhabdas. I closed this ticket https://github.com/jgthms/bulma/issues/1560

**Pull request closed without merging**
