### PR TITLE
recommends ember-bulma as a related project

### PR DESCRIPTION
**Pull request by jbailey4**
Recommending a related project in the README. ember-bulma is an addon specifically for Ember applications, providing a set of UI components styled by Bulma.

/cc @crodriguez1a @alexdiliberto

### CODE REVIEW

**Comment by jgthms** [comment]
Happy to merge, although there's a merge conflict now.

**Comment by jbailey4** [comment]
@jgthms Thanks. Should be good to go now.

**Comment by jbailey4** [comment]
@jgthms ping. merge conflicts are resolved.

**Comment by jgthms** [comment]
Ugh, sorry, I introduced another one.

**Comment by jbailey4** [comment]
@jgthms No problem. Good to go now.

**Comment by jgthms** [comment]
Thanks!

**Pull request merged**
