### PR TITLE
Fixed responsiveness for logo in README.md

### PR DESCRIPTION
**Pull request by scriptcoded**
This is a **documentation fix**.

### Proposed solution
The Bulma logo was not responsive, and stretched oddly on smaller devices. By adding a 600x315 version of the logo, and removing `width="600" height="315"` we manage to keep it responsive.

### Tradeoffs
Virtually none :)

### Testing Done
The solution only adds an extra version of the logo, as well as removes the width and height attributes from the documentation. There should be no problems.

**Before:**
chrome_2018-10-26_07-48-41
**After:**

### CODE REVIEW

**Comment by jgthms** [comment]
The solution is actually to just add `height: auto;` to the image.

**Comment by scriptcoded** [comment]
@jgthms Perhaps I was doing something wrong, but I couldn't get GitHub to accept my inline style. And auto isn't a valid value for the width attribute.

**Comment by jgthms** [comment]
It's for the height, not the width.

**Comment by scriptcoded** [comment]
Is it valid for height then?

**Pull request closed without merging**
