### PR TITLE
Feature/new element badge

### PR DESCRIPTION
**Pull request by Wikiki**
Hi,

Here is a proposal for a new element named "badge" to be able to display a number on text, button, ... as follow:
Badge Element

Regards

### CODE REVIEW

**Comment by jgthms** [comment]
This is pretty nice! It could be available as a **Bulma extension**. I'm thinking of adding an "Extensions" section to the website.

Could you make it available at https://github.com/Wikiki/bulma-badge and a link to the Readme? Thanks.

**Comment by Wikiki** [comment]
Hi,

the extension is available at https://github.com/Wikiki/bulma-badge.

Regards

**Comment by jgthms** [comment]
Fantastic! I'm gonna add an "Extensions" page on the website for components like this, that can like on top of Bulma.

**Comment by jgthms** [comment]
It's live: http://bulma.io/extensions/

**Pull request closed without merging**
