### PR TITLE
Fix #2739 add variables size for layout hero

### LINKED ISSUE #2739: Hero Sizes should be configurable variables
Like done with section sass these hero sizes should be variables: 

https://github.com/jgthms/bulma/blob/5381f2649d3466487585a0f0dfa8f177c8f42b1d/sass/layout/hero.sass#L71-L85

See section sass:
https://github.com/jgthms/bulma/blob/5381f2649d3466487585a0f0dfa8f177c8f42b1d/sass/layout/section.sass#L1-L3

I can make a pull request on it if this seems like something many others would also want.

### PR DESCRIPTION
**Pull request by IvanFrescas**
This is an improvement|documentation fix.

Fixes issue #2739 adding three sass variables to hero layout

### Proposed solution
Screen Shot 2019-12-14 at 9 31 39

### Testing Done
It was tested locally and the layout hero is still working the same way as before.

### Changelog updated?

No.

### CODE REVIEW

**Comment by jgthms** [comment]
So this is a breaking change because you're removing the horizontal padding on the `hero-body` defined [here](https://github.com/jgthms/bulma/blob/master/sass/layout/hero.sass#L143):

```sass
.hero-body
  padding: 3rem 1.5rem
```

I would actually created 4 variables:

```sass
$hero-body-padding
$hero-body-padding-vertical-small
$hero-body-padding-vertical-medium
$hero-body-padding-vertical-large
```

**Comment by IvanFrescas** [comment]
Thanks for your answer, I'll work on it.

**Comment by IvanFrescas** [comment]
What do you think of this solution? 
I also noticed that in the documentation there is no reference to the is-small class. If you want I can make another issue of that.

**Comment by jgthms** [comment]
I'd keep `padding-top` and `padding-bottom` for the `small` `medium` and `large` versions. Otherwise, you're repeating `1.5rem` 4 times.

**Comment by IvanFrescas** [comment]
I relied on the file `section.sass` where it also has the sizes for medium and large.
do you have any suggestions to avoid repeating `1.5rem`?

**Comment by hammadzz** [comment]
> I'd keep `padding-top` and `padding-bottom` for the `small` `medium` and `large` versions. Otherwise, you're repeating `1.5rem` 4 times.

That would be cleaner.


> I relied on the file `section.sass` where it also has the sizes for medium and large.
> do you have any suggestions to avoid repeating `1.5rem`?

Just remove the 1.5rem from medium and large as it is an unnecessarily overriding the same value from hero-body. But I am new to SASS so @jgthms will have to confirm.

**Comment by jgthms** [comment]
Actually you’re right. Doing like `section.sass` is fine actually. Let’s go with that.

**Comment by IvanFrescas** [comment]
Awesome.
So, should I leave the changes as they are? Or should I modify something? 🤔

**Pull request merged**
