### PR TITLE
input[type=range] support

### PR DESCRIPTION
**Pull request by acidjazz**
### Proposed solution

image

Addresses https://github.com/jgthms/bulma/issues/67

### CODE REVIEW

**Comment by acidjazz** [comment]
@jgthms let me know if this PR needs anything else, hope I followed the guidelines correctly w/ these check-ins

**Comment by jgthms** [comment]
Did you just copy the code from vue-bulma/slider repository?? https://github.com/vue-bulma/slider/blob/master/src/Slider.vue

That's... not how you contribute.

**Comment by acidjazz** [comment]
@jgthms actually that component is using SCSS, so not it wasn't a straight copy but i did combine a portion of it converting it to sass with the 2 codepen examples linked in the issue related issue.

Maybe you should elaborate on the issue that you'd like uniquely forged never-been-seen css.. for your slider

**Comment by jhoff** [comment]
I think the important point is that if you're going to use someone else's code you should attribute it appropriately, even if open source to begin with.

**Comment by Wikiki** [comment]
Hi,

you can find an implementation for range for Bulma here: https://wikiki.github.io/bulma-extensions/slider

Regards,

**Comment by acidjazz** [comment]
@jhoff  you're welcome to re-submit the PR crediting all the authors; you can start with the issue related where people have linked examples of the versions they wanted, I remember including a little bit of each one until everyone was happy with the look.

**Pull request closed without merging**
