### PR TITLE
Add Bulma Customizer to related projects

### PR DESCRIPTION
**Pull request by bstashio**
### Proposed solution
[Bulma Customizer](https://bulma-customizer.bstash.io/) was inspired by [Bootstrap Customize](https://getbootstrap.com/customize/).

Currently supports the following main features:
- SASS files
- Variables
- Extensions
- CSS output style

### Tradeoffs
N/A

### Testing Done
N/A

### CODE REVIEW

**Comment by jgthms** [comment]
There's merge conflicts in your PR.

**Comment by bstashio** [comment]
Not sure how that happened. Anyway, that's fixed now.

Any feedback regarding the customizer? If you find it useful, then perhaps the next thing is to include it in the docs, as it's done in bootstrap customize.

I've included @Wikiki and @hunzaboy extensions; have you guys checked it out?

**Comment by Wikiki** [comment]
Hi @bstashio,

thanks for including my extensions in your project.
It's a great idea. Can't you let user customize extensions variables too before building the package ?

Regards,

**Comment by bstashio** [comment]
Hi @Wikiki 

Sure! Extensions variables are now supported.

bulma-customizer-extensions-variables

**Comment by Wikiki** [comment]
Thanks. 
Good luck with this project.

**Comment by bstashio** [comment]
Thanks, I hope the community find it useful.

**Pull request merged**
