### PR TITLE
Add placeholders for extending in other frameworks.

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
Add placeholders for extending in other frameworks.
For example in buefy.

This is a **new feature | improvement | bugfix | documentation fix**.

### Testing Done

None.

### Changelog updated?

No.

`%dropdown-item-a-button, a.dropdown-item,`

Im not sure about this, is this needed here?

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
@jgthms

**Comment by jgthms** [comment]
Why not use `@extend .dropdown-item`?

**Comment by afwn90cj93201nixr2e1re** [comment]
Coz then every custom rules also be extended, that's really anoying.
https://github.com/buefy/buefy/issues/1946 check issue for better understanding.

**Comment by afwn90cj93201nixr2e1re** [comment]
Also one more  question, how i should name placeholder for `.input`?
https://github.com/jgthms/bulma/blob/master/sass/form/input-textarea.sass#L37

coz we already have %input here, should i name it %.input or something else? Like %cInput, where c - class.

**Comment by afwn90cj93201nixr2e1re** [comment]
Also one more  question, how i should name placeholder for `.input`?
https://github.com/jgthms/bulma/blob/master/sass/form/input-textarea.sass#L37

coz we already have %input here, should i name it %.input or something else? Like %cInput, where c - class.

@jgthms

**Comment by afwn90cj93201nixr2e1re** [comment]
@jgthms anything is wrong now? Or you can merge it?

**Comment by afwn90cj93201nixr2e1re** [comment]
https://sass-lang.com/documentation/breaking-changes/extend-compound
https://sass-lang.com/documentation/at-rules/import

Should i close issue and ignore sass docs?

Better to ask you, why are u using placeholders with mixins instead class, and thats the answer.

**Comment by afwn90cj93201nixr2e1re** [comment]
Seems like no-one gives a fuck. Ok.

**Pull request closed without merging**
