### PR TITLE
Fixes #1992 - Disabled form elements hover state is overlapping, if control has add-ons elements

### LINKED ISSUE #1992: Disabled form elements hover state is overlapping, if control has add-ons elements
* This is about **Bulma
* It's a bug

### Overview of the problem

* This is about the Bulma CSS framework
* I'm using Bulma 0.7.1
* My browser is: Chrome v67.0
* I am sure this issue is not a duplicate

### Description

If a form field is disabled and that form field uses has add-on element ( has-addons ), hover state is overlapping to add-on element.

### Steps to Reproduce

1. Visit - https://jsfiddle.net/g9fkzm0v/20/
2. Hover the input element

### Expected behaviour

Don't assign a z-index value to disabled input elements.

### Actual behaviour

Hovered input elements z-index value has been changed, thus add-ons default borders are overlapped. ( z-index value is 2 on hover state )

### PR DESCRIPTION
**Pull request by kdrdgn**
This is a bugfix

Disabled form elements hover state is overlapping if a control has add-ons elements

### Proposed solution

This solution excludes disabled form elements hover state which is used within has-addons fields wrapper
Fixes #1992

### Tradeoffs

No tradeoffs.

### Testing Done
I checkout out master and changed the lines. Please see attached files

#### .fields.has-addons > .control > input : hover bug
field-has-addons-disabled-input-hover-bug

#### .fields.has-addons > .control > input : hover fixes
field-has-addons-disabled-input-hover-fixed

#### example html structure
```html
<div class="field has-addons">
  <p class="control">
    <input class="input" type="text" placeholder="Your email" disabled>
  </p>
  <p class="control">
    <a class="button is-static">
      @gmail.com
    </a>
  </p>
</div>
```

### CODE REVIEW

**Comment by jgthms** [comment]
There’s no change??

**Comment by kdrdgn** [comment]
@jgthms one of animated gif shows overlapping 1px border; the other one is after the fix.

**Comment by jgthms** [comment]
No I mean there’s no code change? The “Changes” shows 0 additions and 0 deletions.

**Comment by kdrdgn** [comment]
@jgthms Oh, I am so sorry, I had pushed a reverted version mistakenly. Now it should be ok.

**Pull request merged**
