### PR TITLE
Fixes #1413 - navbar-menu background-color fix

### LINKED ISSUE #1413: $navbar-background-color does not work after upgrading from 0.5.2 to 0.6.0
This is about Bulma

### Overview of the problem

This is about the Bulma **CSS framework** 
I'm using Bulma 0.6.0
My **browser** is: Firefox 56
### Description

Trying to change the navbar dropdown background color for all elements.  the saas file that works perfectly fine in 0.5.2 no longer works in 0.6.0

The bolded part was added to make it work.

@import "sass/utilities/initial-variables"

$blue: #336699
$navbar-background-color: $blue
$navbar-dropdown-background-color: $blue
$navbar-item-hover-background-color: $blue
$navbar-dropdown-item-hover-background-color: $blue
$navbar-dropdown-item-active-background-color: $blue

$navbar-dropdown-color: $white
$navbar-dropdown-arrow: $white
$navbar-item-color: $white
$navbar-dropdown-item-hover-color: #00FFFF
$navbar-item-hover-color: #00FFFF

$primary: $blue;
$title-color: $blue

@import "bulma"

**.navbar-menu**
x>        **background-color: $blue**

.navbar-burger:hover
x>        background-color: $blue

.navbar-burger.burger.is-active
x>        background-color: $blue
x>        span
xx>                background-color: $white

.navbar-burger
 x>       span
xx>                background-color: $white

Note: "x>" and "xx>" is used to show indentation

### PR DESCRIPTION
**Pull request by Carl-Foster**
This is a **bugfix** for #1413

### Proposed solution

The `.navbar-menu` was not referencing the correct variable. This has been rectified.

### Testing Done

Did the same fix in the local node_modules/bulma folder of a project which overwrote the `$navbar-background-color` variable. Originally, the `navbar-menu` had a white background and after the change, was the `$navbar-background-color` as intended (previous behaviour of <0.6)

### CODE REVIEW

**Comment by jgthms** [comment]
Thanks but there’s some whitespace issue I believe.

**Comment by Carl-Foster** [comment]
Just by the way @jgthms, I've saved this file now as UNIX line endings to fix the whitespace issues, but the `editorconfig` for this project states to use DOS line endings. May want to update that.

**Comment by jgthms** [comment]
Omg yes! That's why so many PRs have whitespace issues. Thanks! I'll fix that right away.

**Comment by Carl-Foster** [comment]
@jgthms is this possible to be merged? I would like to be able to upgrade our bulma version to the latest, but can't due to this bug.

**Comment by jgthms** [comment]
Merged!

**Pull request merged**
