### PR TITLE
Add is-clipped to modal-content

### PR DESCRIPTION
**Pull request by edhenderson**
Changes proposed:

* [x] Add
* [x] Fix
* [ ] Remove
* [ ] Update

- By default the modal allows content to scroll (in both dimensions)
and that is good
- adding an `is-clipped` class means we can force modal to use
`overflow:hidden`

### CODE REVIEW

**Comment by edhenderson** [comment]
@jgthms First commit Sir, great effort so far. I rebased as your recent change bust my small commit.

**Comment by jgthms** [comment]
Thanks but you need to rebuild all the css files. Check the contribution guidelines.

**Comment by edhenderson** [comment]
@jgthms Sorry first contribution so missed that part. Let me check later tonight. Thanks.

**Comment by edhenderson** [comment]
@jgthms OK, good for another look Sir.

**Comment by edhenderson** [comment]
I am not sure what the conflict is here? Can you shed any light?

**Pull request closed without merging**
