### PR TITLE
Adding modifiers on form elements.

### PR DESCRIPTION
**Pull request by wlepinski**
cc @jgthms

### CODE REVIEW

**Comment by wlepinski** [comment]
I also added a `.control-help` class to display messages below/above inputs.

**Comment by jgthms** [comment]
What about textareas and dropdowns? Also, these modifiers would make more sense directly on `.input`, `.textarea`, and `.select`, rather than on the container.

How do the hover/active/focus states look like?

I like the `.control-help` idea. I forgot to implement `<label class="label"></label>` which would have a similar role.

**Comment by arkist** [comment]
also, would need to implement things like `.is-small`. @jgthms do you have any plan for?

**Comment by jgthms** [comment]
@arkist `.is-small` already exists for inputs.

**Comment by arkist** [comment]
@jgthms sure, but not for `select` :joy:

**Comment by jgthms** [comment]
You need to rebuild the css files with `npm run build`.

**Pull request closed without merging**
