### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by jbierfeldt**
This is a **documentation fix**

### Proposed solution

Typo fix

### Changelog updated?

No.

### CODE REVIEW

**Comment by jgthms** [comment]
“maintain” here means to keep going, continue, so I think it’s valid.

**Comment by jbierfeldt** [comment]
If you want to keep maintain, then you could change it to: "To maintain an evenly balanced design, ..."

The current version "To maintain the design evenly balanced" sounds very strange to my ear (U.S. American English), and reads like a typo. But of course maybe it sounds fine in other types of English! Just wanted to raise awareness in case it was a typo.

**Comment by jgthms** [comment]
You're right, the original sentence wasn't great. We could go with `To provide an evenly balanced design` since the sentence is not really a continuation of a prior statement anyway. What do you think?

**Comment by jbierfeldt** [comment]
I think that's perfect!

**Comment by jbierfeldt** [comment]
I actually think that "maintain" is the best option here, since "provide" is used immediately in the next clause. Also, the use of "maintain" in ```To maintain an evenly balanced design``` has the connotation of ```(To allow you, the user,) to maintain an evenly balanced design```.

**Comment by jgthms** [comment]
Ok let's go with that. Thanks for your help.

**Pull request merged**
