### PR TITLE
Add related projects

### PR DESCRIPTION
**Pull request by bokuweb**
Add Bulma with React: https://github.com/bokuweb/re-bulma
I develop Bulma components with React. Please add this project to related projects.

### CODE REVIEW

**Comment by jens1o** [comment]
Could you please remove unused content?

**Comment by bokuweb** [comment]
@jens1o Sorry, removed.

**Comment by mblarsen** [comment]
I'm working on https://github.com/mblarsen/elm-bulma which is an Elm wrapper for bulma. @bokuweb

**Comment by bokuweb** [comment]
@mblarsen re-bulma is react wrapper.

**Pull request closed without merging**
