### PR TITLE
Improvement disable resize in textarea disabled and ignore jekyll-cache

### PR DESCRIPTION
**Pull request by lucasferreiralimax**
This is a ** bugfix and documentation fix**.
This is an improvement for textarea disabled.
This is an improvement ignore .jekyll-cache

### Proposed solution
* Disabled textarea can resize, I disabled resizing with CSS.
* Ignore jekyll-cache in repository
Testing resize on textarea disabled

### Testing Done

Testing resize on textarea really disable resize
Testing resize on textarea really disable

### Changelog updated?

No.

### CODE REVIEW

**Comment by jgthms** [comment]
I agree with removing `.jekyll-cache` but I'm not sure about removing the resize option. For example, the disabled textarea could be filled with useful information to the user, acting like a read-only version of the textarea. So the user might want to resize it.

Can you change this PR and only remove the `.jekyll-cache`?

**Comment by lucasferreiralimax** [comment]
But is disabled, user is not access a feature with a disable
@jgthms  Thinking for to case disabled or not?

**Comment by jgthms** [comment]
Yeah but they can still read it, even if it's disabled.

**Comment by lucasferreiralimax** [comment]
@jgthms But also you see that with scroll

Follow example with resize disabled

Example

**Pull request closed without merging**
