### PR TITLE
add a hint how to use the nav-toggle to be responsive

### PR DESCRIPTION
**Pull request by EdJoPaTo**
Changes proposed:
- [X] Add
- [ ] Fix
- [ ] Remove
- [ ] Update

### CODE REVIEW

**Comment by jruizsulime** [comment]
I'm trying to use the nav on mobile site, but I can't make it working. I'm reading the documentation but still can't know how to use it.

**Comment by maarteNNNN** [comment]
@jruizsulime 

```
this.toggleMenu = () => {
        var burger = document.querySelector('.nav-toggle');
        var menu = document.querySelector('.nav-menu');
        burger.classList.toggle('is-active');
        menu.classList.toggle('is-active');
    }
```

and in the html part

`span.nav-toggle(onClick='{toggleMenu}')`

**Comment by jruizsulime** [comment]
@maarteNNNN Thank you so much for your help; it works as expected. Used jQuery with HTML.

Regards

**Comment by maarteNNNN** [comment]
I forgot -  it's becoming a habit -  I use pug(jade).

**Pull request merged**
