### PR TITLE
Add elm-bulma-classes to readme

### PR DESCRIPTION
**Pull request by Razzeee**
This only updates the readme

### CODE REVIEW

**Comment by Razzeee** [comment]
I'm not sure what the diff is doing.

**Comment by ctolkien** [comment]
Diff is likely due to line endings...

**Comment by Razzeee** [comment]
Not sure why the github editor would touch 80% of the line endings.

**Comment by carlfredrikhero** [comment]
Tip: Add `?w=1` to the Files changed tab to remove whitespace.

https://github.com/jgthms/bulma/pull/1085/files?w=1

**Comment by jgthms** [comment]
It doesn't remove whitespace changes. It only hides them. Can you fork the project and make a clean PR?

**Comment by Razzeee** [comment]
@jgthms Updated. Should be correct now.

On the secound try I used sublime and ended up with something similiar, but only with changed table rows.
Feels like markdown has some weird/invisible whitespaces when doing tables. So my sublime plugin removed the trailing spaces. Still sounds weird.

**Pull request merged**
