### PR TITLE
Feature/Timeline

### PR DESCRIPTION
**Pull request by Wikiki**
See [issue 422](https://github.com/jgthms/bulma/issues/422)

### Description

I've created a new Timeline Feature to easily display a timeline like this
Image of Timeline

**Can you add it to the repository if you like it and if it fits to Bulma coding rules ?**

### HTML Structure

```
<div class="timeline">
     <div class="timeline-item">
          <div class="timeline-item-content">
               <div>5 minutes ago</div>
                    <p><strong><a href="#">John Doe</a></strong> Uploaded a photo <strong>"DSC000586.jpg"</strong></p>
               </div>
          </div>

          <div class="timeline-item">
               <div class="timeline-item-content">
                    <div>30 minutes ago</div>
                         <p><a href="">Lorem</a> commented your post.</p>
                         <p><em>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam laoreet tellus ut tincidunt euismod. "</em></p>
                    </div>
               </div>
          </div>
     </div>
</div>
```

### CODE REVIEW

**Comment by sausin** [comment]
@Wikiki thanks for this! :+1:

**Comment by jgthms** [comment]
Nice one! I don't feel it should be part of the core Bulma styles, but you should make a bulma extension for that, and we'll add to the README instead.

**Comment by giflw** [comment]
Hi @jgthms. Why this shouldn't be part of core Bulma. I was hoping this as a Bulma component. In fact, I'm search a CSS framework that have in its core components like cards, table and timelines. This is really usefull and would make Bulma even more attractive. Best regards.

**Comment by sausin** [comment]
@giflw the component is maintained by @Wikiki and available [here](https://github.com/Wikiki/bulma-timeline) with instructions on using it as an extention.

It is also included on the extensions page at the [bulma](http://bulma.io/extensions/). 

Initially, I was also of the opinion that it would be a great addition to the framework, but since there is an official mention on extensions, this is perhaps a better way of giving credit.

**Comment by giflw** [comment]
Thanks for the instructions :smile:

**Pull request closed without merging**
