### PR TITLE
Add Horizontal Card

### PR DESCRIPTION
**Pull request by Wikiki**
Add Horizontal Card component

Horizontal Card Example

### CODE REVIEW

**Comment by Axieum** [comment]
Came here to add this exact feature. Glad someone else also wants this! 👍

**Comment by HDVinnie** [comment]
Any update? Will this be merged?

**Comment by CreativeBulma** [comment]
I had no feedback :-(

**Comment by HDVinnie** [comment]
well I would love to see this added for sure

**Comment by diomed** [comment]
is html same as for vertical one, or what's the structure?

**Comment by Wikiki** [comment]
Hi @diomed,

the html is the same than for the vertical one.

**Comment by diomed** [comment]
@Wikiki looks like there is no way to reverse image position `<div class="media-right">` does nothing,
when I want image to be on the right side.

**Comment by Wikiki** [comment]
Hi @diomed,

you're right, I'll add that.

**Comment by erickzhao** [comment]
Thanks for making this!

One question: do you think it would be better for the default behavior of this card to revert to vertical for mobile displays?

**Comment by Axieum** [comment]
I agree with @erickzhao! Although, some kind of override should still exist (i.e. `.is-mobile`; like the Level implementation).

**Comment by twaiiiin** [comment]
This does not play well with the aspect ratio modifiers on the image element. `is-4by3` for example.
The aspect ratio is not alway respected because of flexbox, `flex-grow` and `object-fit: cover` I guess...

**Comment by Wikiki** [comment]
Hi,

I'll try to work on it tomorrow.

**Comment by Wikiki** [comment]
Code updated to on mobile (using <code>.is-mobile</code> modifier) and with image size modifiers

**Comment by diomed** [comment]
can image spread to take 3/5 of container?
if yes; how?

**Comment by twaiiiin** [comment]
@diomed I tried to do something like that too.

```
.card.is-horizontal.is-half .card-image {
        flex: 3;
    }
    .card.is-horizontal.is-half .card-content {
        flex: 3;
    }

    .card.is-horizontal.is-quarter .card-image {
        flex: 3;
    }
    .card.is-horizontal.is-quarter .card-content {
        flex: 9;
    }

    .card.is-horizontal.is-third .card-image {
        flex: 4;
    }
    .card.is-horizontal.is-third .card-content {
        flex: 8;
    }

    .card.is-horizontal.is-twothird .card-image {
        flex: 8;
    }
    .card.is-horizontal.is-twothird .card-content {
        flex: 4;
    }
```
You can use these modifiers: `is-half`, `is-quarter`, `is-third`,`is-twothird`.

I hope it helps.

**Comment by diomed** [comment]
@jgthms how is it possible that despite so much interest for some components, they are still not included?

**Comment by DanGSun** [comment]
So? Is it going into Bulma?

**Comment by rishavs** [comment]
Having horizontal cards would be great.

**Comment by cliffpyles** [comment]
@jgthms Would the introduction of visual regression tests help with the maintenance concerns you mentioned? If so – is that something you would be up for as a PR?

**Comment by dewey** [comment]
@Wikiki Thanks for this, used it in my project and works well 👍

**Comment by diomed** [comment]
@dewey could you share bulma.css file with this here?

**Comment by dewey** [comment]
@diomed I just converted the code from the Pull Request to CSS and used that, not sure if there's something in there that I tweaked but this works for me.

```
.card.is-horizontal {
  flex-direction: row;
  display: flex;
  flex-basis: 50ex;
  flex-grow: 0;
  flex-shrink: 1;
  box-shadow: none;
}

.card.is-horizontal .card-image {
  align-self: center;
}

.card.is-horizontal .image {
  min-height: 100%;
}

.card.is-horizontal .card-content {
  flex: 1;
}

.card.is-horizontal .card-content {
  padding-left: 1em;
  padding-top: 0;
  padding-bottom: 0;
  font-size: 0.8em;
}

.card.is-horizontal {
  ul {
    list-style: none;
    margin: 0;
  }

  .is-divider {
    margin-top: 1.5rem;
    margin-bottom: 1rem;
  }
}
```

**Comment by rishavs** [comment]
Any chance of getting this merged? Its been a while and we can really use a feature like this.

**Comment by ShRyDeR** [comment]
This would be great to have

**Comment by adilj13** [comment]
I got it done using [tiles](https://bulma.io/documentation/layout/tiles/) and it is responsive for mobile.

Example for a product item
```
<div class="tile is-parent box">
        <article class="tile is-child is-4">
                <img src="IMAGE_URL" alt="" srcset="">
        </article>
        <article class="tile is-child is-8 is-primary">
                <p class="title is-spaced is-3">PRODUCT_TITLE</p>
                <p class="subtitle is-5">PRODUCT_PRICE</p>
                <p class="content">PRODUCT_DESCRIPTION</p>
        </article>
</div>
```

**Comment by telophase** [comment]
For anyone still looking for this functionality, I created an extension that adds horizontal cards that you can use in the meantime. I still need to add a few features and fine-tune responsive behaviour, but you can do everything the proposal allows you to do (and a bit more!)

https://github.com/telophase/bulma-horizontal-card

**Pull request closed without merging**
