### PR TITLE
is-rounded

### PR DESCRIPTION
**Pull request by oleksiipotiekhin**
This is a **new improvement**.

### Proposed solution
 #1028 Class **is-rounded** was added to other _elements/components_ where it didn't break an esthetics and gave additional functionality to them. The reason behind this is to have ability to create something similar to those UI elements:

Angular

### Testing Done
Tested by running `npm run build` successfully. Also as you can see in attached picture all _elements/components_ were checked manually. Plus manual regression testing was done by checking that _elements/components_ that previously were using **is-rounded** class are still working.

### Additional Notes
I've set `$radius-rounded` to `290486px` as this was the previous value used in **tag** and **delete** _elements/components_. Please let me know if you like this idea and i will update documentation also. This pull request contains only `sass` changes

is-rounded
Buttons

### CODE REVIEW

**Comment by connectkushal** [comment]
@oleksiipotiekhin nice work man.  Hope this is merged but if it is not, please do make it a plugin :)

**Comment by Wikiki** [comment]
Wonderful job ;-)

**Comment by TheRandomMelon** [comment]
Hopefully this gets merged, it'd be so useful

**Comment by jgthms** [comment]
I like the idea, thanks. But we need to augment the horizontal padding, because it doesn't look good like this.

**Comment by oleksiipotiekhin** [comment]
Just please let me know if you will need any help.

**Comment by pavi2410** [comment]
@jgthms Please try to merge this

**Comment by jgthms** [comment]
It needs work, as mentioned above.

**Comment by oleksiipotiekhin** [comment]
@jgthms I've increased the horizontal padding by `0.25em` in buttons, tabs and pagination.

Padding

**Comment by koddr** [comment]
Awesome work! Can’t wait to add this to new version! 👍

**Comment by jgthms** [comment]
Merged it. There were still some issues but I'll fix them before doing a release.

**Pull request merged**
