### PR TITLE
Add navbar color modifiers

### PR DESCRIPTION
**Pull request by devmattrick**
### Proposed solution
Adds is-* modifiers to the navbar.

### Tradeoffs
This increases the size of Bulma's built CSS.

### Testing Done
[Here](https://i.imgur.com/SZpeJ1q.png) is a screenshot showing off the colored navbars. This PR resolves issue #842.

Please let me know if you would like any changes to be made.

### CODE REVIEW

**Comment by ctolkien** [comment]
Presumably this would allow `is-black` to have a dark/inverse nav? This would be awesome.

**Comment by devmattrick** [comment]
@ctolkien 

Yep, it should work like the button element. Any color that's defined in the `$colors` array will work.

**Comment by BiosElement** [comment]
Strongly support this. Would be great for showing the difference between different areas of a site without majorly changing the branding.

**Comment by ctolkien** [comment]
@jgthms - any interest in getting this in?
@devmattrick  - are you able to resolve the conflicts to get this up to date?

**Comment by alireza6677** [comment]
Seems good 👍

**Comment by chasegiunta** [comment]
Just the thing I needed! Would love to have this in @jgthms.

**Comment by Wikiki** [comment]
Hi,

I'm waiting for it :-)
is it possible to get the same thing for menu component ?

Regards,

**Pull request merged**
